[project]
name = "pdf2img"
version = "0.1.2"
description = "A simple CLI tool for converting pdfs to images!"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "typer[all]",
    "rich",
    "PyMuPDF"
]

[project.scripts]
pdf2img = "pdf2img.cli:app"

[tool.setuptools]
packages = ["pdf2img"]
package-dir = {"" = "src"}
